### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/iele-semantics#6]
The entire IELE semantics needs to be documented at the same level of detail as the EVM yellowpaper

**Comment by grosu** [comment]
@dwightguth I think we should not follow the yellowpaper as an example.  The Ethereum foundation itself appears to be interested in switch to our KEVM semantics as a reference EVM semantics.  Philip and Everett implemented some Pandoc/Sphinx tools that generate, from the KEVM semantics, the following: https://thehydra.io/evm/.  We can use the same tools they used.

**Comment by dwightguth** [comment]
To be clear I mean only that we provide the level of detail of the yellow paper, not that we imitate the yellow paper itself. I'm perfectly fine doing what you describe as long as it provides sufficient detail.
