### ISSUE TITLE
IELE assembler

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/iele-semantics#8]
We need a conversion from llvm-like textual representation of IELE to binary bytecode representation. This means translation of string labels to integer labels, translation of string register names to integer register numbers, and translation from ssa-like assignment expressions to the instruction representation of each instruction. This should also include changes to the IELE semantics syntax productions where necessary to make the syntax used by the semantics as close as possible to the final syntax of the assembly.

**Comment by traiansf** [comment]
Do we have a parser for the textual representation of IELE?  Should we use / extend (a fragment of) LLVM?

**Comment by grosu** [comment]
@traiansf we need to come up with a nice syntax for the IELE language.  Just started this discussion on slack.  Also added integration with github, so we can see messages we write here on github also in slack.
